version: "3"

services:
  nuxt:
    build: ./app/
    container_name: sticker-cord-site
    restart: always
    command:
      "yarn start"

    networks:
      - web
    labels:
      - traefik.enabled=true
      - traefik.backend=ctv-post-creator
      - traefik.frontend.rule=Host:api.ctv.daniel-stefan.dev
      - traefik.docker.network=web
      - traefik.port=3000
networks:
  web:
    external: true